{
 "title": "Train data",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed History",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    { "expr": "train_speed", "legendFormat": "Speed (km/h)" },
    { "expr": "train_internet", "legendFormat": "Internet connectivity" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_trip", "legendFormat": "{{train}}" }
   ]
  },
  {
   "title": "Current Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_trip", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Internet connectivity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_internet", "legendFormat": "{{connectivity}}" }
   ]
  },
  {
   "title": "Next Station",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_trip", "legendFormat": "{{next_station}}" }
   ]
  },
  {
   "title": "Distance to Next Station",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_distance", "legendFormat": "__auto" }
   ]
  }
 ]
}