{
 "title": "Train data",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Speed History",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg_over_time(train_speed[30s])",
     "legendFormat": "Speed (km/h)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_trip", "legendFormat": "{{train}}" }
   ]
  },
  {
   "title": "Current Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(train_trip) by ()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Internet connectivity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(train_internet) by ()", "legendFormat": "{{connectivity}}" }
   ]
  },
  {
   "title": "Next Station",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_trip", "legendFormat": "{{next_station}}" }
   ]
  },
  {
   "title": "Distance to Next Station",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "train_distance", "legendFormat": "__auto" }
   ]
  }
 ]
}