name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
    with:
      composer: false

  python-checks:
    name: 'Perform Python checks'
    runs-on: ubuntu-latest

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

      - name: 'Setup Python'
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3
          cache: 'pip'

      - name: 'Install dependencies'
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: 'Lint Editorconfig'
        run: ec -verbose

      - name: 'Lint Python files'
        run: pylint lib/*.py

      - name: 'Lint shell files'
        run: bash -c 'shopt -s globstar nullglob; shellcheck *.sh'
