name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@c5d066ebd1c130e32d87bf7e7c8a1c3ca64bd14b # 0.8.2

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@c5d066ebd1c130e32d87bf7e7c8a1c3ca64bd14b # 0.8.2
    with:
      composer: false

  python-checks:
    name: 'Perform Python checks'
    runs-on: ubuntu-latest

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@c5d066ebd1c130e32d87bf7e7c8a1c3ca64bd14b # 0.8.2

      - name: 'Setup Python'
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3
          cache: 'pip'

      - name: 'Install dependencies'
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: 'Lint Editorconfig'
        run: ec -verbose

      - name: 'Lint Python files'
        run: pylint lib/*.py

      - name: 'Lint shell files'
        run: bash -c 'shopt -s globstar nullglob; shellcheck *.sh'
