name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: 'Create release'
    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@1fb632290bce95f37a13857172e1ac6bf1a821c1 # 0.8.3
